#!/usr/bin/env python3
"""
Fetch Toronto matcha cafes from OpenStreetMap (Overpass API)
and export to a CSV ready to import into the `places` table.

Schema:
  id        uuid  (generated on insert, left blank here)
  osm_id    varchar(50)
  name      varchar(255)
  address   text
  lat       double precision
  lng       double precision
  image_url text   (OSM has no images; left blank — enrich separately)
  cached_at timestamptz (filled to current UTC time)
"""

import csv
import json
import sys
import time
from datetime import datetime, timezone
from typing import Optional

import requests

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
OVERPASS_URL = "https://overpass-api.de/api/interpreter"

# Toronto bounding box  (south, west, north, east)
BBOX = (43.5810, -79.6393, 43.8555, -79.1168)

# Keywords that indicate a matcha place.
# We query OSM for all cafes/tea shops, then filter client-side.
MATCHA_KEYWORDS = ["matcha", "macha", "ceremonial", "sencha", "hojicha", "japanese tea"]

# Overpass query: nodes + ways tagged as cafe or tea (Toronto bbox)
OVERPASS_QUERY = """
[out:json][timeout:60];
(
  node["amenity"="cafe"]({s},{w},{n},{e});
  node["shop"="tea"]({s},{w},{n},{e});
  node["cuisine"~"japanese|matcha",i]({s},{w},{n},{e});
  way["amenity"="cafe"]({s},{w},{n},{e});
  way["shop"="tea"]({s},{w},{n},{e});
);
out center tags;
""".format(s=BBOX[0], w=BBOX[1], n=BBOX[2], e=BBOX[3])

OUTPUT_FILE = "toronto_matcha_places.csv"
CSV_FIELDS = ["id", "osm_id", "name", "address", "lat", "lng", "image_url", "cached_at"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def fetch_overpass(query: str, retries: int = 3) -> dict:
    for attempt in range(1, retries + 1):
        try:
            print(f"  → Querying Overpass API (attempt {attempt})…")
            resp = requests.post(
                OVERPASS_URL,
                data={"data": query},
                timeout=90,
                headers={"User-Agent": "TorontoMatchaScraper/1.0"},
            )
            resp.raise_for_status()
            return resp.json()
        except requests.RequestException as exc:
            print(f"  ✗ Request failed: {exc}")
            if attempt < retries:
                wait = 10 * attempt
                print(f"  Retrying in {wait}s…")
                time.sleep(wait)
            else:
                sys.exit("Could not reach Overpass API after multiple attempts.")


def build_address(tags: dict) -> str:
    parts = []
    for key in ("addr:housenumber", "addr:street", "addr:city", "addr:province", "addr:postcode"):
        if tags.get(key):
            parts.append(tags[key])
    return ", ".join(parts) if parts else ""


def is_matcha_place(tags: dict) -> bool:
    searchable = " ".join(
        str(v).lower()
        for k, v in tags.items()
        if k in ("name", "alt_name", "description", "cuisine", "menu", "operator", "brand")
    )
    return any(kw in searchable for kw in MATCHA_KEYWORDS)


def element_to_row(el: dict) -> Optional[dict]:
    tags = el.get("tags", {})
    name = tags.get("name", "").strip()
    if not name:
        return None
    if not is_matcha_place(tags):
        return None

    # Coordinates — nodes have lat/lon directly; ways expose a "center"
    if el["type"] == "node":
        lat, lng = el.get("lat"), el.get("lon")
    else:
        center = el.get("center", {})
        lat, lng = center.get("lat"), center.get("lon")

    if lat is None or lng is None:
        return None

    osm_id = f"{el['type'][0]}{el['id']}"   # e.g. n123456 or w789012

    return {
        "id": "",                           # generated by Postgres
        "osm_id": osm_id,
        "name": name,
        "address": build_address(tags),
        "lat": lat,
        "lng": lng,
        "image_url": "",                    # not available from OSM
        "cached_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("🍵  Toronto Matcha Places — OSM Fetcher")
    print("=" * 50)

    print("\n[1/3] Fetching data from OpenStreetMap Overpass API…")
    data = fetch_overpass(OVERPASS_QUERY)
    elements = data.get("elements", [])
    print(f"  ✓ Received {len(elements)} raw elements")

    print("\n[2/3] Filtering for matcha-related places…")
    rows = []
    seen_osm_ids = set()
    for el in elements:
        row = element_to_row(el)
        if row and row["osm_id"] not in seen_osm_ids:
            rows.append(row)
            seen_osm_ids.add(row["osm_id"])

    print(f"  ✓ Found {len(rows)} matcha place(s):")
    for r in rows:
        print(f"      • {r['name']}  ({r['lat']:.5f}, {r['lng']:.5f})")

    print(f"\n[3/3] Writing CSV → {OUTPUT_FILE}")
    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  ✓ Done — {len(rows)} rows written to {OUTPUT_FILE}")
    print("\n💡 Import hint:")
    print("   COPY places (osm_id, name, address, lat, lng, image_url, cached_at)")
    print(f"   FROM '{OUTPUT_FILE}' CSV HEADER;")
    print("\n   Or with psql:")
    print(f"   \\copy places (osm_id, name, address, lat, lng, image_url, cached_at) FROM '{OUTPUT_FILE}' CSV HEADER;")


if __name__ == "__main__":
    main()
