#!/usr/bin/env python3
"""
Fetch Toronto matcha places from Foursquare Places API
and export to a CSV ready to import into the `places` table.

Usage:
    export FSQ_API_KEY="your_key_here"
    python fetch_matcha_foursquare.py

Schema:
    id        uuid   — left blank (generated by Postgres on insert)
    osm_id    varchar(50) — repurposed as fsq_id (unique Foursquare place ID)
    name      varchar(255)
    address   text
    lat       double precision
    lng       double precision
    image_url text
    cached_at timestamptz
"""

import csv
import io
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

# Force UTF-8 output on Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
FSQ_API_KEY = os.environ.get("FSQ_API_KEY", "")

FSQ_SEARCH_URL = "https://api.foursquare.com/v3/places/search"
FSQ_PHOTOS_URL = "https://api.foursquare.com/v3/places/{fsq_id}/photos"

# Toronto city centre coordinates
TORONTO_LL = "43.6532,-79.3832"
TORONTO_RADIUS_M = 15_000          # 15 km radius covers the whole city

# Search queries — Foursquare ranks by relevance, so cast a wide net
SEARCH_QUERIES = ["matcha", "matcha cafe", "japanese tea", "matcha latte"]

# Foursquare category IDs to restrict results (cafes + tea houses)
# 13032 = Café, 13274 = Tea Room, 13025 = Coffee Shop
FSQ_CATEGORY_IDS = "13032,13274,13025"

OUTPUT_FILE = "toronto_matcha_places.csv"
CSV_FIELDS = ["id", "osm_id", "name", "address", "lat", "lng", "image_url", "cached_at"]

def _headers():
    return {
        "Authorization": FSQ_API_KEY,
        "Accept": "application/json",
    }


# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def make_request(url: str, params: dict = None, retries: int = 3) -> dict | list | None:
    """Make a GET request with retries using urllib (avoids Windows IncompleteRead bug in requests)."""
    if params:
        url = f"{url}?{urllib.parse.urlencode(params)}"
    for attempt in range(1, retries + 1):
        try:
            req = urllib.request.Request(url, headers=_headers())
            with urllib.request.urlopen(req, timeout=20) as r:
                return json.loads(r.read().decode())
        except urllib.error.HTTPError as e:
            if e.code == 401:
                sys.exit("✗ Invalid API key. Check your FSQ_API_KEY environment variable.")
            if e.code == 429:
                print(f"\n  ✗ Rate limited — waiting 60s…")
                time.sleep(60)
                continue
            raise
        except Exception as e:
            if attempt < retries:
                print(f"\n  ⚠ Attempt {attempt} failed ({e}), retrying…", flush=True)
                time.sleep(2 * attempt)
            else:
                raise
    return None


def search_places(query: str) -> list[dict]:
    """Search Foursquare for places matching a query near Toronto."""
    params = {
        "query": query,
        "ll": TORONTO_LL,
        "radius": TORONTO_RADIUS_M,
        "categories": FSQ_CATEGORY_IDS,
        "limit": 50,
        "fields": "fsq_id,name,location,geocodes,categories",
    }
    try:
        data = make_request(FSQ_SEARCH_URL, params=params)
        return data.get("results", []) if data else []
    except Exception as e:
        print(f"  ✗ Search error for '{query}': {e}")
        return []


def fetch_photo(fsq_id: str) -> str:
    """Return the best available photo URL for a place, or empty string."""
    try:
        photos = make_request(
            FSQ_PHOTOS_URL.format(fsq_id=fsq_id),
            params={"limit": 1, "sort": "POPULAR"},
        )
        if photos:
            p = photos[0]
            return f"{p['prefix']}original{p['suffix']}"
    except Exception:
        pass
    return ""


def build_address(location: dict) -> str:
    parts = []
    if location.get("address"):
        parts.append(location["address"])
    if location.get("locality"):
        parts.append(location["locality"])
    if location.get("region"):
        parts.append(location["region"])
    if location.get("postcode"):
        parts.append(location["postcode"])
    return ", ".join(parts)


def place_to_row(place: dict, image_url: str) -> dict:
    geocodes = place.get("geocodes", {}).get("main", {})
    location = place.get("location", {})
    return {
        "id": "",
        "osm_id": place["fsq_id"],          # stored in osm_id column as unique external ID
        "name": place.get("name", ""),
        "address": build_address(location),
        "lat": geocodes.get("latitude", ""),
        "lng": geocodes.get("longitude", ""),
        "image_url": image_url,
        "cached_at": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not FSQ_API_KEY:
        sys.exit(
            "✗ FSQ_API_KEY is not set.\n"
            "  Run:  export FSQ_API_KEY='your_key_here'  then retry."
        )

    print("🍵  Toronto Matcha Places — Foursquare Fetcher")
    print("=" * 52)

    # ── Step 1: Collect all unique places across all search queries ──────────
    print(f"\n[1/3] Searching Foursquare with {len(SEARCH_QUERIES)} queries…")
    seen_ids: dict[str, dict] = {}

    for query in SEARCH_QUERIES:
        print(f"  → '{query}'…", end=" ", flush=True)
        results = search_places(query)
        new = 0
        for place in results:
            fsq_id = place.get("fsq_id")
            if fsq_id and fsq_id not in seen_ids:
                seen_ids[fsq_id] = place
                new += 1
        print(f"{len(results)} results, {new} new")
        time.sleep(0.3)   # be a polite API citizen

    print(f"  ✓ {len(seen_ids)} unique places found")

    # ── Step 2: Fetch one photo per place ────────────────────────────────────
    print(f"\n[2/3] Fetching photos ({len(seen_ids)} places)…")
    rows = []
    for i, (fsq_id, place) in enumerate(seen_ids.items(), 1):
        name = place.get("name", "?")
        print(f"  [{i:02d}/{len(seen_ids)}] {name}", end=" … ", flush=True)
        image_url = fetch_photo(fsq_id)
        rows.append(place_to_row(place, image_url))
        print("📷" if image_url else "—")
        time.sleep(0.2)

    # ── Step 3: Write CSV ─────────────────────────────────────────────────────
    print(f"\n[3/3] Writing CSV → {OUTPUT_FILE}")
    with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)

    print(f"  ✓ Done — {len(rows)} rows written to {OUTPUT_FILE}")

    print("\n💡 Import into Postgres:")
    print("   \\copy places (osm_id, name, address, lat, lng, image_url, cached_at)")
    print(f"   FROM '{OUTPUT_FILE}' CSV HEADER;")
    print()
    print("   Note: osm_id column holds the Foursquare fsq_id as the unique external key.")


if __name__ == "__main__":
    main()
